### ISSUE TITLE
generalize `bilinmalg` too?

### ISSUE THREAD

**Issue by CohenCyril** [math-comp/Coq-Combi#1]
https://github.com/hivert/Coq-Combi/blob/a335c43e7fe7bc90b7f13bf38a8e94f954349800/theories/Dendri/shufflealg.v#L82-L85

I guess that if you generalize this too, you could also capture bilinear forms (and possibly get a dot product by providing an appropriate `f`?)

By the way are you aware of this: https://github.com/math-comp/math-comp/pull/207 ?

**Comment by hivert** [comment]
Done (generalizing). Concerning #207. I knew you had something like that but didi't knew where. No I know. Thanks !
