### ISSUE TITLE
Link to doc broken

### ISSUE THREAD

**Issue by darijgr** [math-comp/Coq-Combi#12]
Thanks for the update! Installation has become really easy, to the point I can just "make" and run coqide and it works; I've been waiting for this for years.

The [link to the doc](https://hivert.github.io/Coq-Combi/) in README.md is broken, though, as are many other links on your website. Some changes in the folder structure perhaps?

Also, I'd love to see some kind of "reading order" recommendation, telling me in what order to read the .v files to understand them. I know I could make a toposort of their dependencies (is there a one-line way to do that, by the way?), but a properly curated list could be better, particularly if it comes with brief explanations of what the files are doing. For example, looking at partition.v, I really have no clue what this here means:
`Definition in_shape sh b := b.2 < nth 0 sh b.1.`
Besides, there are probably specific chapters in the MCB book and files in the MathComp doc I should read beforehand.

**Comment by hivert** [comment]
Hi @darijgr. I'm very happy to have you looking at my code and commenting it ! 

The link to the doc is now fixed (I was waiting for a pull request in math-comp to be integrated). This should make the reading order more easy to find (https://math-comp.github.io/combi/1.0.0/index.html). For the definition like `in_shape` they should be documented at the top of the file (see https://math-comp.github.io/combi/1.0.0/Combi.Combi.partition.html). That said, this is my first time I documented such a thing. So there is clearly room for improvement and any suggestion or even PR are welcome.

Note that the release was a beta one. I'm planning to make the definitive one in a few days, once those little details are fixed.
