### ISSUE TITLE
Any chance of mathcomp 2.0 compatibility?

### ISSUE THREAD

**Issue by darijgr** [math-comp/Coq-Combi#5]
I've recently installed MathComp but found myself unable to compile this due to breaking changes in MathComp. Anyone planning to rebase this? If not, I'll just downgrade my MathComp; but I'd rather know in advance if the issue will be moot in a week :)

**Comment by hivert** [comment]
I @darijgr . I recently created a branch for compatibility with MathComp 2.  See https://github.com/math-comp/Coq-Combi/tree/mathcomp2

**Comment by darijgr** [comment]
Thank you!
